service: import-service
plugins:
  - serverless-offline
  - serverless-webpack
  - serverless-dotenv-plugin
package:
  individually: false
  excludeDevDependencies: false
provider:
  name: aws
  region: eu-west-1
  runtime: nodejs12.x
  apiGateway:
    minimumCompressionSize: 1024
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:GetObject
        - s3:PutObject
        - s3:DeleteObject
        - s3:ListObjects
      Resource: arn:aws:s3:::shumsky-s3/*
functions:
  importProductsFile:
    handler: handlers/import-products-file.handler
    events:
      - http:
          method: get
          path: import
          cors: true
          request:
            parameters:
              querystrings:
                name: true
  importFileParser:
    handler: handlers/import-file-parser.handler
    events:
      - s3:
          event: s3:ObjectCreated:*
          bucket: shumsky-s3
          rules:
            - prefix: uploaded/
            - suffix: .csv
          existing: true

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules:
      packagePath: ../../package.json
  dotenv:
    path: .env
    logging: false
